// Copyright (c) 2026 Steven Kreutzer. All rights reserved.
// Proprietary and confidential. Unauthorized copying, modification, or
// distribution of this file, via any medium, is strictly prohibited.
//
// Extracted from KSix Prep Studio without behavioural change. Import paths were
// rewritten, host generated types replaced with the structurally identical ones
// in core/prepSettings.ts, and `ImageData` annotations swapped for PixelBuffer —
// which ImageData satisfies structurally, so a browser host passes its own
// objects straight in.

export interface QuickPaletteColor {
  name: string;
  hex: string;
  group: string;
}

export interface BackgroundRemovalPreset {
  label: string;
  description: string;
}

export interface QuickMachinePreset {
  label: string;
  targetDpi: number;
  cleanupAggression: number;
  colorTolerance: number;
  contrast: number;
  saturation: number;
  sharpen: number;
  posterize: number;
  halftoneDefault: boolean;
  transparentBackground: boolean;
  preserveSoftEdges: boolean;
  allowVectorize: boolean;
  notes: string;
}

export const KSIX_PALETTE: QuickPaletteColor[] = [
  { name: "Process Black", hex: "#1A1A1A", group: "Neutrals" },
  { name: "Rich Black", hex: "#0D0D0D", group: "Neutrals" },
  { name: "Cool Gray", hex: "#6B7280", group: "Neutrals" },
  { name: "Silver", hex: "#C0C0C0", group: "Neutrals" },
  { name: "White", hex: "#FFFFFF", group: "Neutrals" },
  { name: "KSix Red", hex: "#DC2626", group: "Reds" },
  { name: "Crimson", hex: "#991B1B", group: "Reds" },
  { name: "Coral", hex: "#F87171", group: "Reds" },
  { name: "Rust", hex: "#92400E", group: "Reds" },
  { name: "KSix Orange", hex: "#EA580C", group: "Oranges" },
  { name: "Pumpkin", hex: "#C2410C", group: "Oranges" },
  { name: "Gold", hex: "#D97706", group: "Yellows" },
  { name: "KSix Yellow", hex: "#FBBF24", group: "Yellows" },
  { name: "Lemon", hex: "#FDE68A", group: "Yellows" },
  { name: "Forest Green", hex: "#15803D", group: "Greens" },
  { name: "KSix Green", hex: "#16A34A", group: "Greens" },
  { name: "Lime", hex: "#84CC16", group: "Greens" },
  { name: "Teal", hex: "#0F766E", group: "Greens" },
  { name: "KSix Blue", hex: "#1D4ED8", group: "Blues" },
  { name: "Sky Blue", hex: "#0EA5E9", group: "Blues" },
  { name: "Navy", hex: "#1E3A5F", group: "Blues" },
  { name: "Cerulean", hex: "#0284C7", group: "Blues" },
  { name: "KSix Purple", hex: "#7C3AED", group: "Purples" },
  { name: "Violet", hex: "#6D28D9", group: "Purples" },
  { name: "Lavender", hex: "#A78BFA", group: "Purples" },
  { name: "Magenta", hex: "#DB2777", group: "Pinks" },
  { name: "Hot Pink", hex: "#EC4899", group: "Pinks" },
  { name: "Rose", hex: "#FDA4AF", group: "Pinks" },
  { name: "Brown", hex: "#78350F", group: "Browns" },
  { name: "Tan", hex: "#D4A574", group: "Browns" },
  { name: "Cream", hex: "#FEF3C7", group: "Browns" },
];

export const BACKGROUND_REMOVAL_PRESETS: Record<string, BackgroundRemovalPreset> = {
  auto: {
    label: "Auto Detect",
    description: "Automatically detects and removes the dominant background color.",
  },
  white: {
    label: "Remove White",
    description: "Removes white and near-white pixels from the background.",
  },
  dark: {
    label: "Remove Dark",
    description: "Removes dark and black pixels from the background.",
  },
  logo: {
    label: "Logo Mode",
    description: "Tolerance-based selection optimized for logos and vector artwork.",
  },
  product: {
    label: "Product Photo",
    description: "Removes studio backgrounds from product photography.",
  },
};

export const MACHINE_PRESETS: Record<string, QuickMachinePreset> = {
  dtf: {
    label: "DTF Transfer",
    targetDpi: 300,
    cleanupAggression: 55,
    colorTolerance: 45,
    contrast: 8,
    saturation: 12,
    sharpen: 55,
    posterize: 0,
    halftoneDefault: false,
    transparentBackground: true,
    preserveSoftEdges: false,
    allowVectorize: true,
    notes: "Export as transparent PNG at 300 DPI. White ink will be auto-generated by the RIP.",
  },
  uvdtf: {
    label: "UVDTF Gang Sheet",
    targetDpi: 300,
    cleanupAggression: 70,
    colorTolerance: 30,
    contrast: 15,
    saturation: 8,
    sharpen: 65,
    posterize: 4,
    halftoneDefault: false,
    transparentBackground: true,
    preserveSoftEdges: false,
    allowVectorize: true,
    notes: "Hard edges required. Export transparent PNG. Small text and fine details may need manual cleanup.",
  },
  uv: {
    label: "UV Print",
    targetDpi: 360,
    cleanupAggression: 45,
    colorTolerance: 50,
    contrast: 8,
    saturation: 10,
    sharpen: 40,
    posterize: 0,
    halftoneDefault: false,
    transparentBackground: false,
    preserveSoftEdges: true,
    allowVectorize: false,
    notes: "Include white underbase layer for dark substrates. Export at 360 DPI minimum.",
  },
  sublimation: {
    label: "Sublimation",
    targetDpi: 300,
    cleanupAggression: 35,
    colorTolerance: 60,
    contrast: 12,
    saturation: 20,
    sharpen: 30,
    posterize: 0,
    halftoneDefault: false,
    transparentBackground: false,
    preserveSoftEdges: true,
    allowVectorize: false,
    notes: "Mirror the image for sublimation transfer. Boost saturation — colors will appear muted before pressing.",
  },
  fineart: {
    label: "Fine Art Print",
    targetDpi: 600,
    cleanupAggression: 20,
    colorTolerance: 70,
    contrast: 5,
    saturation: 5,
    sharpen: 20,
    posterize: 0,
    halftoneDefault: false,
    transparentBackground: false,
    preserveSoftEdges: true,
    allowVectorize: false,
    notes: "Minimal processing. Use ICC color profile for the paper stock. Export at 600 DPI or higher.",
  },
  poster: {
    label: "Poster / Banner",
    targetDpi: 150,
    cleanupAggression: 35,
    colorTolerance: 55,
    contrast: 12,
    saturation: 15,
    sharpen: 35,
    posterize: 0,
    halftoneDefault: false,
    transparentBackground: false,
    preserveSoftEdges: true,
    allowVectorize: false,
    notes: "Large format — 150 DPI is sufficient when viewed at distance. Boost contrast slightly for outdoor use.",
  },
  laser: {
    label: "Laser Engrave",
    targetDpi: 500,
    cleanupAggression: 80,
    colorTolerance: 20,
    contrast: 25,
    saturation: 0,
    sharpen: 80,
    posterize: 2,
    halftoneDefault: true,
    transparentBackground: true,
    preserveSoftEdges: false,
    allowVectorize: true,
    notes: "Convert to grayscale depth map. Dark = deep burn, light = shallow. Export as PNG or SVG.",
  },
  vinyl: {
    label: "Vinyl Cut",
    targetDpi: 300,
    cleanupAggression: 75,
    colorTolerance: 25,
    contrast: 20,
    saturation: 0,
    sharpen: 70,
    posterize: 2,
    halftoneDefault: false,
    transparentBackground: true,
    preserveSoftEdges: false,
    allowVectorize: true,
    notes: "Vectorize output for cutting. Single-color or spot-color only. Minimum 1/8 inch detail.",
  },
};
